
debug: true
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/articles
    username:
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # none, create ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR