
debug: true
server:
  port: 8080
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/blog
    url: jdbc:postgresql://tea-blog-server.postgres.database.azure.com:5432/?user=vaobmawius&password=6RlN3G0SM89OnbKLoliE&sslmode=require
    username:
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # none, create ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR